"""Bundle data/*.json + data/annotations/ into site/js/data.js for the static site.

Runs in CI after scrape.py; can also run locally if Python is installed.
"""
from __future__ import annotations

import datetime
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def load(name: str):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def main() -> None:
    annotations = {}
    anno_dir = DATA / "annotations"
    for f in sorted(anno_dir.glob("*.json")):
        a = json.loads(f.read_text(encoding="utf-8"))
        annotations[a["item_id"]] = a

    contested = DATA / "contested-nay-rows.json"
    notes = DATA / "motion-notes.json"

    def load_optional(name, default):
        p = DATA / name
        return json.loads(p.read_text(encoding="utf-8")) if p.exists() else default

    def load_dir(sub):
        p = DATA / sub
        return [json.loads(f.read_text(encoding="utf-8")) for f in sorted(p.glob("*.json"))] if p.exists() else []

    payload = {
        "generated": datetime.date.today().isoformat(),
        "councilors": load("councilors.json"),
        "items": load("items.json"),
        "meetings": load("meetings.json"),
        "contested_rows": load("contested-nay-rows.json") if contested.exists() else [],
        "motion_notes": load("motion-notes.json") if notes.exists() else {},
        "tags": load_optional("tags.json", {}),
        "committee_votes": load_optional("committee-votes.json", {}),
        "major_votes": load_optional("major-votes.json", []),
        "statements": load_optional("statements.json", []),
        "policies": load_optional("policies.json", []),
        "storylines": load_dir("storylines"),
        "dossiers": load_dir("dossiers"),
        "annotations": annotations,
    }
    out = ROOT / "site" / "js" / "data.js"
    out.write_text(
        "/* Generated by scraper/build_site_data.py — do not edit by hand. */\n"
        "window.PDX = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8",
    )
    stamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    idx = ROOT / "site" / "index.html"
    html = idx.read_text(encoding="utf-8")
    html = re.sub(r"js/data\.js\?v=[^\"]*", f"js/data.js?v={stamp}", html)
    html = re.sub(r"js/app\.js\?v=[^\"]*", f"js/app.js?v={stamp}", html)
    idx.write_text(html, encoding="utf-8")
    print(f"wrote {out}: {len(payload['items'])} items, "
          f"{len(payload['meetings'])} meetings, {len(annotations)} annotations; stamp {stamp}")


if __name__ == "__main__":
    main()
