# PowerShell twin of build_site_data.py for machines without Python.
# The data files are already valid JSON, so this simply assembles them verbatim —
# no ConvertFrom/To-Json round-trip (PS 5.1 mangles nested arrays).
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File scraper\build_site_data.ps1
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$data = Join-Path $root "data"

function Read-Raw($path) { (Get-Content -LiteralPath $path -Raw -Encoding UTF8).Trim() }

$annoParts = @()
Get-ChildItem (Join-Path $data "annotations") -Filter *.json | Sort-Object Name | ForEach-Object {
    $raw = Read-Raw $_.FullName
    $id = ($raw | ConvertFrom-Json).item_id   # scalar property read is safe in PS 5.1
    $annoParts += ('"{0}": {1}' -f $id, $raw)
}

$generated = Get-Date -Format "yyyy-MM-dd"
$contestedPath = Join-Path $data "contested-nay-rows.json"
$contested = if (Test-Path $contestedPath) { Read-Raw $contestedPath } else { "[]" }
$json = @"
{
"generated": "$generated",
"councilors": $(Read-Raw (Join-Path $data "councilors.json")),
"items": $(Read-Raw (Join-Path $data "items.json")),
"meetings": $(Read-Raw (Join-Path $data "meetings.json")),
"contested_rows": $contested,
"annotations": { $($annoParts -join ",`n") }
}
"@

$out = Join-Path $root "site\js\data.js"
$content = "/* Generated by scraper/build_site_data.ps1 - do not edit by hand. */`nwindow.PDX = $json;`n"
[IO.File]::WriteAllText($out, $content, (New-Object Text.UTF8Encoding $false))
Write-Host "wrote $out ($($annoParts.Count) annotations)"
