# PowerShell twin of build_site_data.py for machines without Python.
# The data files are already valid JSON, so this simply assembles them verbatim —
# no ConvertFrom/To-Json round-trip (PS 5.1 mangles nested arrays).
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File scraper\build_site_data.ps1
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$data = Join-Path $root "data"

function Read-Raw($path) { (Get-Content -LiteralPath $path -Raw -Encoding UTF8).Trim() }

$annoParts = @()
Get-ChildItem (Join-Path $data "annotations") -Filter *.json | Sort-Object Name | ForEach-Object {
    $raw = Read-Raw $_.FullName
    $id = ($raw | ConvertFrom-Json).item_id   # scalar property read is safe in PS 5.1
    $annoParts += ('"{0}": {1}' -f $id, $raw)
}

function Read-Optional($name, $default) {
    $p = Join-Path $data $name
    if (Test-Path $p) { Read-Raw $p } else { $default }
}
function Read-DirArray($sub) {
    $p = Join-Path $data $sub
    if (-not (Test-Path $p)) { return "[]" }
    $parts = Get-ChildItem $p -Filter *.json | Sort-Object Name | ForEach-Object { Read-Raw $_.FullName }
    if (-not $parts) { return "[]" }
    "[`n" + ($parts -join ",`n") + "`n]"
}

$generated = Get-Date -Format "yyyy-MM-dd"
$contestedPath = Join-Path $data "contested-nay-rows.json"
$contested = if (Test-Path $contestedPath) { Read-Raw $contestedPath } else { "[]" }
$notesPath = Join-Path $data "motion-notes.json"
$motionNotes = if (Test-Path $notesPath) { Read-Raw $notesPath } else { "{}" }
$json = @"
{
"generated": "$generated",
"councilors": $(Read-Raw (Join-Path $data "councilors.json")),
"items": $(Read-Raw (Join-Path $data "items.json")),
"meetings": $(Read-Raw (Join-Path $data "meetings.json")),
"contested_rows": $contested,
"motion_notes": $motionNotes,
"tags": $(Read-Optional "tags.json" "{}"),
"committee_votes": $(Read-Optional "committee-votes.json" "{}"),
"major_votes": $(Read-Optional "major-votes.json" "[]"),
"statements": $(Read-Optional "statements.json" "[]"),
"policies": $(Read-Optional "policies.json" "[]"),
"storylines": $(Read-DirArray "storylines"),
"dossiers": $(Read-DirArray "dossiers"),
"annotations": { $($annoParts -join ",`n") }
}
"@

$out = Join-Path $root "site\js\data.js"
$content = "/* Generated by scraper/build_site_data.ps1 - do not edit by hand. */`nwindow.PDX = $json;`n"
[IO.File]::WriteAllText($out, $content, (New-Object Text.UTF8Encoding $false))

$stamp = Get-Date -Format "yyyyMMddHHmmss"
$idx = Join-Path $root "site\index.html"
$html = Get-Content -LiteralPath $idx -Raw -Encoding UTF8
$html = $html -replace 'js/data\.js\?v=[^"]*', "js/data.js?v=$stamp" -replace 'js/app\.js\?v=[^"]*', "js/app.js?v=$stamp"
[IO.File]::WriteAllText($idx, $html, (New-Object Text.UTF8Encoding $false))
Write-Host "wrote $out ($($annoParts.Count) annotations); cache stamp $stamp"
